#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.cdsoftware.paperless.targetplatform
./plugin-builder $DEBUG_MODE ../com.cdsoftware.paperless ../com.cdsoftware.paperless.test
